# Site settings

title: "Ferocious Truth"
url: "https://FerociousTruth.com"
encoding: utf-8
permalink: /:year/:title/
collections:
  thought-experiments:
    output: true
    layout: thought-experiment
paginate: 5
paginate_path: "/page-:num"
repository: FerociousTruth/FerociousTruth.github.io
author:
  name: J Thomas Moros
  email: J@FerociousTruth.com

# Build settings
markdown: kramdown
incremental: false # still experimental and seems to be causing problems
strict_front_matter: true

plugins:
  - jekyll-redirect-from

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - ts/

# Front Matter Defaults
defaults:
  -
    scope:
      path: "" # any file path
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # any file path
      type: "thought-experiments"
    values:
      layout: "thought-experiment"
